- name: OSPF
  hosts: all
  become: yes
  tasks:
    - name: disable assymetric routing blocking
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '0'
        sysctl_set: true
        state: present
        reload: true

    - name: copy frr.conf
      template:
        src: frr.conf2.j2
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: '0640'

    - name: restart frr daemon
      systemd:
        name: frr
        state: restarted
        enabled: true
